Repository TeamDeli/Deli-Front, pull requests merged in 2021-08, with the labels that each got.

#16 Feature/filtering/#7
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/images/deli_edited.png
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBarElements.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/LandingPage/LandingPage.js
  src/pages/LandingPage/Sections/Datas.js
  src/pages/LandingPage/Sections/RadioBox.css
  src/pages/LandingPage/Sections/RadioBox.js
  src/pages/LandingPage/Sections/RangeSlider.js
  src/reportWebVitals.js
  src/setupTests.js
  testing_data_sorin.json
  yarn.lock
Labels: feature, sorin

#13 Feature/profile/#3
  kiyeon.json
  package-lock.json
  src/App.js
  src/components/profile/Friends.js
  src/components/profile/UserInfo.js
  src/lib/api/dummyApi.js
  src/pages/Profile.js
Labels: feature, kiyeon

#20 Feature/main/#19
  package-lock.json
  package.json
  src/App.js
Labels: bug, kiyeon

#23 Feature/friends/#4
  src/App.css
  src/App.js
  src/components/friends/Friends.js
  src/components/friends/UserInfo.js
  src/components/friends/WishList.js
  src/components/friends/WishTest.js
  src/components/friends/bingsu.jpeg
  src/pages/AddFriends.js
  src/pages/Test.js
Labels: feature, jueun

#25 Feature/product info/#6
  src/App.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBarElements.js
  src/components/product/ProductRecommend.js
  src/pages/Product.js
Labels: feature, kyungmin

#27 Feature/calendar/#14
  src/App.js
  src/Calendar.css
  src/components/calendar/AddEventModal.js
  src/components/calendar/FriendEvent.js
  src/components/calendar/RemoveEventModal.js
  src/pages/Calendar.js
Labels: bug, taeyeon

#28 Feature/profile/#26
  src/components/profile/Friends.js
  src/components/profile/UserInfo.js
  src/components/profile/WishList.js
  src/pages/Profile.js
Labels: feature, kiyeon

#30 Feature/friends/#29
  src/components/friends/Friends.js
  src/components/friends/UserInfo.js
  src/components/friends/WishList.js
Labels: jueun

#38 Feature/search/#24
  src/App.js
  src/components/product/ProductInformation.js
  src/pages/LandingPage/LandingPage.js
  src/pages/LandingPage/Sections/Datas.js
  src/pages/LandingPage/Sections/RadioBox.js
  src/pages/LandingPage/Sections/RangeSlider.js
  src/pages/Product.js
  src/pages/ProductsByFunction.js
Labels: feature, sorin

#33 Feature/calendar/#14
  src/Calendar.css
  src/pages/Calendar.js
Labels: feature, taeyeon

#34 Feature/profile/#31
  src/components/profile/Friends.js
  src/components/profile/UserInfo.js
  src/components/profile/WishList.js
  src/lib/api.js
  src/pages/Profile.js
Labels: feature, kiyeon

#42 Feature/search/#24
  src/App.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBarElements.js
  src/components/NavBar/SearchFeature.js
  src/components/product/ProductInformation.js
  src/pages/LandingPage/LandingPage.js
  src/pages/LandingPage/Sections/Datas.js
  src/pages/ProductsByFunction.js
Labels: feature, sorin

#41 Feature/add friends/#29
  src/components/friends/Friends.js
  src/components/friends/UserInfo.js
  src/components/friends/WishList.js
  src/components/profile/WishList.js
  src/pages/AddFriends.js
Labels: feature, jueun

#37 feat: 네비게이션바에 프로필 추가, 링크 붙이기
  src/components/NavBar/NavBar.js
Labels: feature, kiyeon
